name: "Health Check"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *' # Run every day at 12:00

jobs:
  check-health-of-websites:
    name: "Health Check of websites related to 3fs.no"
    runs-on: ubuntu-latest

    steps:
      - name: "Ping 3fs.no and check the response"
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://www.3fs.no/|http://www.3fs.no/|3fs.no
          follow-redirect: true
          max-attempts: 2
          retry-delay: 30s

      - name: "Ping paal-erik.no and check the response"
        uses: jtalk/url-health-check-action@v4
        with:
          url: http://paal-erik.no/|paal-erik.no
          follow-redirect: true
          max-attempts: 2
          retry-delay: 30s

      - name: "Ping trefellingspesialisten.no and check the response"
        uses: jtalk/url-health-check-action@v4
        with:
          url: http://trefellingspesialisten.no/|trefellingspesialisten.no
          follow-redirect: true
          max-attempts: 2
          retry-delay: 30s

      - name: "Ping trefellings-spesialisten.no and check the response"
        uses: jtalk/url-health-check-action@v4
        with:
          url: http://trefellings-spesialisten.no/|trefellings-spesialisten.no
          follow-redirect: true
          max-attempts: 2
          retry-delay: 30s
